name: Code complexity analysis
on:
  workflow_dispatch:
  schedule:
   - cron: '15 3 * * *'
jobs:
  scc_job:
    if: ${{ false }}  # sc-11621
    runs-on: [self-hosted, swift-docker]
    timeout-minutes: 60
    name: A job to count the lines of code.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2
        with:
          args: /github/workspace
      - name: SCC
        run: |
          echo '${{ steps.scc.outputs.scc }}'
